<?php

namespace Database\Seeders;

use App\Office;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OfficesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        Office::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        Office::create([
            'country' => 'Nigeria',
            'city' => 'Abuja',
            'key' => '',
            'flag' => 'Nigeria.svg',
            'address' => 'No.5 Onitsha Crescent && Off Gimbiya Street && Area 11, Garki',
            'email' => 'infoabuja@oisservices.com',
            'phone' => '+2348174477018',
            'working_time' => '8:30 am -  4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Netherlands',
            'city' => 'The Hague',
            'key' => 'THE_HAGUE',
            'flag' => 'Netherlands.svg',
            'address' => 'First Floor, Regus Building && Koningin Juliana Plein 10 && 2595AA && Central station',
            'email' => 'infothehague@oisservices.com',
            'phone' => '0031708915324 - 0031687382130',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Turkey',
            'city' => 'Ankara',
            'key' => 'ANKARA',
            'flag' => 'Turkey.svg',
            'address' => 'Buyukesat Mahallesi && Ugur Mumcu\'nun Sokagi && Konak Apartmani && No:49/3 Cankaya',
            'email' => 'infoankara@oisservices.com',
            'phone' => '00903124382175 - 00903124382176',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Atlanta',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => '918 Holcomb Bridge Road && Suite 204 && Roswell && GA 30076',
            'email' => 'infoatlanta@oisservices.com',
            'phone' => '+1 404-695-6373',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Beijing',
            'key' => 'BEIJING',
            'flag' => 'China.svg',
            'address' => 'Suite 908 && Building B Kunsha Centre && No. 16 Xin Yuan Li Street && Chaoyang District',
            'email' => 'infobeijing@oisservices.com',
            'phone' => '+010-84004549',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Lebanon',
            'city' => 'Beirut',
            'key' => 'BEIRUT',
            'flag' => 'Lebanon.svg',
            'address' => 'Lebanon Jnah-Beirut Opposite Rafik Hariri University Hospital Mais 6',
            'email' => 'infobeirut@oisservices.com',
            'phone' => '009611845138',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Egypt',
            'city' => 'Cairo',
            'key' => 'CAIRO',
            'flag' => 'Egypt.svg',
            'address' => '2nd floor, 51-Elnoor St && Eldoki, Giza',
            'email' => 'infocairo@oisservices.com',
            'phone' => '+20 237627293 - +20 237627294',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'SUNDAYS - THURSDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Cape Town',
            'key' => '',
            'flag' => 'SouthAfrica.svg',
            'address' => 'No 50, Long Street',
            'email' => 'infocpt@oisservices.com',
            'phone' => '+27 210133161',
            'working_time' => '9:00 am - 12:00 pm && 1:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - WEDNESSDAY - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Chicago',
            'key' => 'CHICAGO',
            'flag' => 'USA.svg',
            'address' => '4001 West Devon && Suite 509 && IL 60646 ',
            'email' => 'Infochicago@oisservices.com',
            'phone' => '+1 (773) 733-4600',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United Arab Emirates',
            'city' => 'Dubai',
            'key' => 'DUBAI',
            'flag' => 'UAE.svg',
            'address' => '22A (22nd floor) && Silver Tower, Cluster I && Jumeirah Lake Towers',
            'email' => 'infodubai@oisservices.com',
            'phone' => '+971 4 276 5448',
            'working_time' => '9:00 am -  3:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Guangzhou',
            'key' => 'GUANGZHOU',
            'flag' => 'China.svg',
            'address' => 'Room 8E, 8th floor && Wingkin Square && No.29 Jianshe 6 malu && Yuexiu District',
            'email' => 'infoguangzhou@oisservices.com',
            'phone' => '+8620-37812021',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Houston',
            'key' => 'Houston',
            'flag' => 'USA.svg',
            'address' => '9894 Bissonnet Street && Suite 745 && TX 77036',
            'email' => 'infohouston@oisservices.com',
            'phone' => '+1 713 771 1871',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Johannesburg',
            'key' => 'JOHANNESBURG',
            'flag' => 'SouthAfrica.svg',
            'address' => '6 Bolton Road Parkwood Rosebank && 2193',
            'email' => 'infojoburg@oisservices.com',
            'phone' => '+27112682376, +27112682470',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United Kingdom',
            'city' => 'London',
            'key' => 'LONDON',
            'flag' => 'UK.svg',
            'address' => '56-57 Fleet Street && EC4Y 1JU',
            'email' => 'info@oisservices.com',
            'phone' => '02078320000',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Los Angeles',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => '5757 W. Century Boulevard && 90045',
            'email' => 'infola@oisservices.com',
            'phone' => '+1 301231 7000',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Spain',
            'city' => 'Madrid',
            'key' => '',
            'flag' => 'Spain.svg',
            'address' => 'C.de Maudes, 62. && 28003',
            'email' => 'infomadrid@oisservices.com',
            'phone' => '+442078320014',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'India',
            'city' => 'Mumbai',
            'key' => 'MUMBAI',
            'flag' => 'India.svg',
            'address' => 'Plot No. C-38/39 && Parinee Crescenzo && G-Block, 12th Floor && Bandra Kurla Complex && Bandra East && Taluka-Andheri && Mumbai - 400051 && Maharashtra',
            'email' => 'infodelhi@oisservices.com',
            'phone' => '+91 8800530119',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'India',
            'city' => 'New Delhi',
            'key' => '',
            'flag' => 'India.svg',
            'address' => 'C/O Central Board of Irrigation & Power Plot No. 4 && Ground Floor && Institutional Area && Malcha Marg && Chanakyapuri && New Delhi-110021',
            'email' => 'infodelhi@oisservices.com',
            'phone' => '+91 8800530119',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 4:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'New York',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => '370 Lexington Ave && Suite 613 && NY 10017',
            'email' => 'infony@oisservices.com',
            'phone' => '(+1)917-900-1114',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'France',
            'city' => 'Paris',
            'key' => 'PARIS',
            'flag' => 'France.svg',
            'address' => '9 Rue Paul Valery && 75116',
            'email' => 'infoparis@oisservices.com',
            'phone' => '+33 1 83 92 77 81',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Africa',
            'city' => 'Pretoria',
            'key' => '',
            'flag' => 'SouthAfrica.svg',
            'address' => '3rd Floor && Building 2 Brooklyn Bridge Office Park Pretoria && 570 Fehrsen',
            'email' => 'infopret@oisservices.com',
            'phone' => '0270124336314',
            'working_time' => '9:00 am - 12:00 pm && 1:30 pm - 4:40 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Italy',
            'city' => 'Rome',
            'key' => 'ROME',
            'flag' => 'Italy.svg',
            'address' => 'Solutions S.R.L. && Via Sicilia && 30 00187',
            'email' => 'inforome@oisservices.com',
            'phone' => '+39 (0)6 4201 2121',
            'working_time' => '9:30 am - 12:30 pm && 2:00 pm - 3:30 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'China',
            'city' => 'Shanghai',
            'key' => 'SHANGHAI',
            'flag' => 'China.svg',
            'address' => 'Room 506A && Zhongguancun Science Building && No.2911 North Zhongshan Road && Putuo',
            'email' => 'infoshanghai@oisservices.com',
            'phone' => '+86-2161670991',
            'working_time' => '9:00 am -  4:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Washington DC',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => '11900 Parklawn Drive && Suite 160 && MD 20852',
            'email' => 'infowashingtondc@oisservices.com',
            'phone' => '(+1) 301-231-7000',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Germany',
            'city' => 'Berlin',
            'key' => '',
            'flag' => 'Germany.svg',
            'address' => 'Warmensteinacher Straße 59a && 12349',
            'email' => 'N.A',
            'phone' => 'N.A',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Morocco',
            'city' => 'Rabat',
            'key' => '',
            'flag' => 'Morocco.svg',
            'address' => 'Millennium Business Centre && Av. Mehdi Ben Barka && Rabat 10170',
            'email' => 'N.A',
            'phone' => 'N.A',
            'working_time' => 'N.A',
            'working_days' => 'N.A',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Turkey',
            'city' => 'Istanbul',
            'key' => '',
            'flag' => 'Turkey.svg',
            'address' => 'OIS Istanbul Sahrayıcedit Mahallesi && Atatürk Caddesi && Onur İş Merkezi && B Blok && No:3/7 Kadıköy',
            'email' => 'infoistanbul@oisservices.com',
            'phone' => '009 0216 385 79 41',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United Kingdom',
            'city' => 'Manchester',
            'key' => '',
            'flag' => 'UK.svg',
            'address' => 'Regus ST JAMES TOWER && Charlotte Street && M1 4DZ',
            'email' => 'infomanchester@oisservices.com',
            'phone' => 'N.A',
            'working_time' => '9:00 am - 12:00 pm && 2:00 pm - 5:00 pm',
            'working_days' => 'MONDAYS - FRIDAYS',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Germany',
            'city' => 'Frankfurt',
            'key' => '',
            'flag' => 'Germany.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Hungary',
            'city' => 'Budapest',
            'key' => '',
            'flag' => 'Hungary.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Ireland',
            'city' => 'Dublin',
            'key' => '',
            'flag' => 'Ireland.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Belgium',
            'city' => 'Brussels',
            'key' => '',
            'flag' => 'Belgium.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Sweden',
            'city' => 'Stockholm',
            'key' => '',
            'flag' => 'Sweden.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Austria',
            'city' => 'Vienna',
            'key' => '',
            'flag' => 'Austria.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Romania',
            'city' => 'Bucharest',
            'key' => '',
            'flag' => 'Romania.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Poland',
            'city' => 'Warsaw',
            'key' => '',
            'flag' => 'Poland.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Portugal',
            'city' => 'Lisbon',
            'key' => '',
            'flag' => 'Portugal.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Greece',
            'city' => 'Athens',
            'key' => '',
            'flag' => 'Greece.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Cyprus',
            'city' => 'Nicosia',
            'key' => '',
            'flag' => 'Cyprus.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Switzerland',
            'city' => 'Bern',
            'key' => '',
            'flag' => 'Switzerland.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Qatar',
            'city' => 'Doha',
            'key' => '',
            'flag' => 'Qatar.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Japan',
            'city' => 'Tokyo',
            'key' => '',
            'flag' => 'Japan.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'South Korea',
            'city' => 'Seoul',
            'key' => '',
            'flag' => 'SouthKorea.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Thailand',
            'city' => 'Bangkok',
            'key' => '',
            'flag' => 'Thailand.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Hong Kong',
            'city' => 'Hong Kong',
            'key' => '',
            'flag' => 'HongKong.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Singapore',
            'city' => 'Singapore',
            'key' => '',
            'flag' => 'Singapore.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Australia',
            'city' => 'Canberra',
            'key' => '',
            'flag' => 'Australia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Brazil',
            'city' => 'Brasilia',
            'key' => '',
            'flag' => 'Brazil.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Jamaica',
            'city' => 'Kingston',
            'key' => '',
            'flag' => 'Jamaica.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Uganda',
            'city' => 'Kampala',
            'key' => '',
            'flag' => 'Uganda.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Sudan',
            'city' => 'Khartoum',
            'key' => '',
            'flag' => 'Sudan.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Pakistan',
            'city' => 'Islamabad',
            'key' => '',
            'flag' => 'Pakistan.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Russia',
            'city' => 'Moscow',
            'key' => '',
            'flag' => 'Russia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Senegal',
            'city' => 'Dakar',
            'key' => '',
            'flag' => 'Senegal.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Saudi Arabia',
            'city' => 'Riyadh',
            'key' => '',
            'flag' => 'SaudiArabia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'United States',
            'city' => 'Minneapolis',
            'key' => '',
            'flag' => 'USA.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Canada',
            'city' => 'Ottawa',
            'key' => '',
            'flag' => 'Canada.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Mauritius',
            'city' => 'Port Louis',
            'key' => '',
            'flag' => 'Mauritius.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Australia',
            'city' => 'Sidney',
            'key' => '',
            'flag' => 'Australia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Saudi Arabia',
            'city' => 'Jeddah',
            'key' => '',
            'flag' => 'SaudiArabia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
        Office::create([
            'country' => 'Saudi Arabia',
            'city' => 'Makkah',
            'key' => '',
            'flag' => 'SaudiArabia.svg',
            'address' => 'COMING SOON',
            'email' => '',
            'phone' => '',
            'working_time' => '',
            'working_days' => '',
            'postal' => '',
            'providedby' => '',
        ]);
    }
}
